import { coverPage, disclaimer, heading, subheading, subsubheading, para, boldPara, bullet, richPara, createTable, pageBreak, spacer, createDoc, saveDoc, TODAY } from './doc-utils.mjs';

const sections = [
  ...coverPage('Product Description &\nSystem Architecture', 'Comprehensive Technical Overview', '1.0', TODAY),
  ...disclaimer(),

  heading('1. EXECUTIVE SUMMARY'),
  para('Monde is a digital payment system designed to provide accessible, secure, and affordable financial services to the people of Zambia. The platform enables users to send and receive money, top up their digital wallets, withdraw funds, and conduct cashless transactions through an intuitive mobile application available on Android and iOS devices.'),
  para('Monde leverages modern technology infrastructure to deliver real-time payment processing, robust security controls, and a seamless user experience. The system integrates with established mobile money operators in Zambia, including Airtel Money, MTN Money, and Zamtel Kwacha, as well as major banking institutions including FNB, Zanaco, and Absa, through certified payment gateway partners.'),
  para('The Monde platform operates as a closed-loop digital wallet system with interoperability features that allow users to move funds between their Monde wallet and their existing mobile money or bank accounts. All transactions are denominated in Zambian Kwacha (ZMW).'),

  heading('2. PRODUCT DESCRIPTION'),
  subheading('2.1 Core Services'),
  para('Monde offers the following core payment services to its users:'),

  subsubheading('2.1.1 Person-to-Person (P2P) Payments'),
  para('Users can send money to other Monde users instantly using the recipient phone number, QR code, or NFC (Near Field Communication) tap. P2P payments are processed in real-time with immediate balance updates for both sender and recipient.'),
  bullet('Transfer via phone number lookup'),
  bullet('Transfer via QR code scanning'),
  bullet('Transfer via NFC contactless tap'),
  bullet('Transaction confirmation with PIN verification'),
  bullet('Optional transaction notes for record-keeping'),

  subsubheading('2.1.2 Wallet Top-Up (Loading Funds)'),
  para('Users can load funds into their Monde wallet from external sources including mobile money accounts (Airtel Money, MTN Money, Zamtel Kwacha) and bank accounts (via card collection). The top-up process initiates a collection request through the Lipila payment gateway.'),
  bullet('Mobile money collection from Airtel, MTN, and Zamtel'),
  bullet('Card-based collection from FNB, Zanaco, and Absa accounts'),
  bullet('Linked account management for quick repeat top-ups'),

  subsubheading('2.1.3 Withdrawal (Cashing Out)'),
  para('Users can withdraw funds from their Monde wallet to their mobile money accounts or bank accounts. Withdrawals are processed through the Lipila payment gateway disbursement service.'),
  bullet('Mobile money disbursement to Airtel, MTN, and Zamtel'),
  bullet('Bank disbursement to FNB, Zanaco, and Absa accounts'),
  bullet('Linked account selection for quick repeat withdrawals'),

  subsubheading('2.1.4 Agent Network Services'),
  para('Monde operates an agent network that provides cash-in (deposit) and cash-out services for users who prefer cash-based transactions. Agents are verified individuals or businesses authorized to facilitate these transactions.'),
  bullet('Cash-In (Deposit): Agents accept physical cash from customers and credit their Monde wallets. Agents earn a 0.5% commission on each deposit, paid by Monde from the fee ledger.'),
  bullet('Cash-Out: Customers request a cash-out from an agent, who disburses physical cash and debits the customer Monde wallet. Tiered fees apply (K2.50 to K50.00), split 70/30 between agent and Monde.'),
  bullet('Agent-to-Agent Transfer: Agents can transfer float between each other for liquidity management, with a daily cap of K50,000.'),

  subsubheading('2.1.5 QR Code Payments'),
  para('Monde generates unique QR codes for each user that encode their phone number, name, and handle. Other users can scan these QR codes to initiate instant payments without manual phone number entry, reducing errors and improving speed.'),

  subsubheading('2.1.6 NFC Contactless Payments'),
  para('On compatible devices, Monde supports NFC-based contactless payments, allowing users to tap phones together to initiate a payment. This feature leverages the device native NFC hardware for peer-to-peer data exchange.'),

  pageBreak(),
  subheading('2.2 Account Tiers and Limits'),
  para('Monde implements a tiered account system to manage risk and comply with regulatory requirements. Each tier has defined balance and daily transaction limits:'),
  createTable(
    ['Account Tier', 'Maximum Balance', 'Daily Transaction Limit', 'Target Segment'],
    [
      ['Copper (Default)', 'K100,000', 'K20,000', 'Standard users'],
      ['Gold', 'K250,000', 'K50,000', 'Active users, small businesses'],
      ['Platinum', 'K500,000', 'K100,000', 'High-volume users, businesses'],
    ]
  ),
  spacer(),
  para('Tier upgrades are managed exclusively by system administrators through the admin dashboard, ensuring proper due diligence is conducted before increasing any user limits.'),

  subheading('2.3 User Registration and Onboarding'),
  para('New users register through the following process:'),
  bullet('Step 1: User downloads the Monde app from the Google Play Store or Apple App Store.'),
  bullet('Step 2: User provides their full name, Zambian phone number, and preferred mobile money provider.'),
  bullet('Step 3: Phone number is verified via a one-time password (OTP) sent via SMS through Twilio Verify.'),
  bullet('Step 4: User creates a 4-digit Personal Identification Number (PIN) for transaction authorization.'),
  bullet('Step 5: A unique user handle is automatically generated in the format @firstname.lastname.'),
  bullet('Step 6: User account is created with Copper tier (default limits) and a zero balance.'),

  heading('3. SYSTEM ARCHITECTURE'),
  subheading('3.1 Architecture Overview'),
  para('Monde employs a modern, cloud-native architecture built on industry-standard components. The system follows a client-server model with the mobile application communicating with backend services through secure API endpoints.'),

  subsubheading('3.1.1 Architecture Components'),
  para('The system architecture consists of the following key layers:'),
  boldPara('1. Client Layer (Mobile Application)'),
  bullet('Built with React Native and Expo framework for cross-platform compatibility (Android and iOS)'),
  bullet('Expo Router for type-safe navigation'),
  bullet('Zustand state management for efficient local state handling'),
  bullet('Expo SecureStore for encrypted local credential storage'),
  bullet('Camera integration for QR code scanning'),
  bullet('NFC module for contactless payments'),

  boldPara('2. API Gateway and Authentication Layer'),
  bullet('Supabase Authentication (GoTrue) for user identity management'),
  bullet('Phone-based authentication with PIN (converted to secure password)'),
  bullet('JWT (JSON Web Token) based session management with automatic refresh'),
  bullet('Row-Level Security (RLS) policies for database access control'),

  boldPara('3. Application Backend'),
  bullet('PostgreSQL database (Supabase-hosted) for persistent data storage'),
  bullet('Supabase Edge Functions (Deno runtime) for serverless business logic'),
  bullet('Remote Procedure Calls (RPCs) for atomic transaction processing'),
  bullet('Realtime subscriptions for live balance and transaction updates'),

  boldPara('4. Payment Gateway Layer'),
  bullet('Lipila Payment Gateway for mobile money and bank integrations'),
  bullet('Supports MoMo collections (Airtel, MTN, Zamtel) and card collections'),
  bullet('Supports MoMo disbursements and bank disbursements'),
  bullet('Asynchronous callback handling for payment status updates'),

  boldPara('5. Infrastructure Layer'),
  bullet('Supabase Cloud hosted on Amazon Web Services (AWS)'),
  bullet('Region: South Africa (af-south-1) for low-latency Zambian access'),
  bullet('Automatic backups, point-in-time recovery'),
  bullet('DDoS protection and SSL/TLS encryption'),

  pageBreak(),
  subheading('3.2 System Architecture Diagram'),
  para('[DIAGRAM: The following describes the system architecture flow]', { bold: true, italics: true }),
  spacer(),
  para('Mobile App (React Native) --[HTTPS/TLS]--> Supabase API Gateway --[JWT Auth]--> PostgreSQL Database'),
  para('Mobile App --[HTTPS/TLS]--> Supabase Edge Functions --[HTTPS]--> Lipila Payment Gateway'),
  para('Lipila Gateway --[MoMo API]--> Airtel Money / MTN Money / Zamtel Kwacha'),
  para('Lipila Gateway --[Bank API]--> FNB / Zanaco / Absa'),
  para('Lipila Gateway --[Callback]--> Supabase Edge Function (lipila-callback)'),
  para('PostgreSQL --[Realtime]--> Mobile App (live balance/transaction updates)'),
  spacer(),
  para('Note: A formal system architecture diagram with visual components will be prepared for the PowerPoint presentation to the Bank of Zambia.', { italics: true }),

  subheading('3.3 Data Flow'),
  subsubheading('3.3.1 P2P Payment Flow'),
  bullet('1. Sender initiates payment (enters recipient phone, amount, confirms with PIN)'),
  bullet('2. Mobile app calls process_payment RPC via Supabase'),
  bullet('3. RPC validates: sender balance, frozen status, daily limits, tier limits, recipient existence'),
  bullet('4. Atomic database transaction: debit sender, credit recipient, calculate and collect fees, create transaction records'),
  bullet('5. Realtime notification pushed to both sender and recipient apps'),
  bullet('6. Both users see updated balances immediately'),

  subsubheading('3.3.2 Top-Up Flow'),
  bullet('1. User selects top-up amount and funding source (mobile money or bank card)'),
  bullet('2. App calls create_pending_topup RPC to create a pending transaction'),
  bullet('3. Edge Function calls Lipila API to initiate collection from user mobile money or card'),
  bullet('4. User approves payment on their mobile money provider (USSD prompt or card authorization)'),
  bullet('5. Lipila sends callback to lipila-callback Edge Function with payment status'),
  bullet('6. On success: pending transaction is confirmed, user balance is credited'),

  subsubheading('3.3.3 Withdrawal Flow'),
  bullet('1. User selects withdrawal amount and destination (mobile money or bank account)'),
  bullet('2. App calls process_withdraw RPC to debit user wallet and create transaction'),
  bullet('3. Edge Function calls Lipila API to initiate disbursement to user account'),
  bullet('4. Lipila processes disbursement and sends callback with status'),
  bullet('5. On success: transaction is confirmed; on failure: funds are reversed to user wallet'),

  pageBreak(),
  heading('4. THIRD-PARTY INTEGRATIONS'),

  subheading('4.1 Lipila Payment Gateway'),
  para('Monde integrates with Lipila (https://lipila.io), a licensed payment gateway operating in Zambia, for processing mobile money and bank card transactions. Lipila provides:'),
  bullet('Mobile Money Collections: Airtel Money, MTN Money, Zamtel Kwacha'),
  bullet('Mobile Money Disbursements: Airtel Money, MTN Money, Zamtel Kwacha'),
  bullet('Card Collections: Visa/Mastercard via FNB, Zanaco, Absa'),
  bullet('Bank Disbursements: Direct bank transfers'),
  bullet('Real-time webhook callbacks for transaction status updates'),
  para('All communication with Lipila uses HTTPS with API key authentication. Sandbox and production environments are fully separated.'),

  subheading('4.2 Twilio Verify'),
  para('Phone number verification during user registration and PIN recovery is handled through Twilio Verify, a globally recognized SMS verification service. Twilio Verify provides:'),
  bullet('SMS-based one-time password (OTP) delivery'),
  bullet('Automatic OTP generation and validation'),
  bullet('Rate limiting and fraud prevention'),
  bullet('Global SMS delivery network with Zambian operator coverage'),

  subheading('4.3 Supabase Cloud'),
  para('The backend infrastructure is hosted on Supabase Cloud, which provides:'),
  bullet('Managed PostgreSQL database with automated backups'),
  bullet('Authentication service (GoTrue) with phone-based auth support'),
  bullet('Edge Functions runtime (Deno) for serverless business logic'),
  bullet('Realtime engine for live data subscriptions'),
  bullet('Row-Level Security (RLS) for fine-grained access control'),
  bullet('Hosted on AWS with SOC2 Type II compliance'),

  heading('5. SECURITY MEASURES'),
  para('A comprehensive description of security measures is provided in the separate document: "Security Features and Cyber Security Policy." Key highlights include:'),
  bullet('End-to-end TLS 1.3 encryption for all data in transit'),
  bullet('AES-256 encryption for data at rest (database and backups)'),
  bullet('PIN-based authentication with secure password derivation'),
  bullet('Row-Level Security (RLS) policies ensuring users can only access their own data'),
  bullet('JWT-based session management with automatic token refresh'),
  bullet('Expo SecureStore for encrypted credential storage on device'),
  bullet('ProGuard/R8 code obfuscation for Android builds'),
  bullet('Rate limiting on authentication endpoints'),
  bullet('Anti-fraud controls including circular transaction detection and daily limits'),
  bullet('Production logging hardened to prevent sensitive data leakage'),

  heading('6. SETTLEMENT PROCESS'),
  para('A detailed settlement process description is provided in the separate document: "Settlement Process." Monde settles transactions through:'),
  bullet('Real-time internal ledger settlement for P2P transactions (instant)'),
  bullet('Lipila gateway settlement for mobile money and bank transactions (T+0 to T+1)'),
  bullet('Fee collection into a dedicated fee ledger account'),
  bullet('Administrative revenue withdrawal capability'),

  heading('7. CYBERSECURITY MEASURES'),
  para('Comprehensive cybersecurity measures are detailed in the "Security Features and Cyber Security Policy" and "Risk Management Framework" documents. These include infrastructure-level protections, application-level controls, and operational security procedures.'),

  heading('8. DOCUMENT REFERENCES'),
  para('This document forms part of the Monde designation application package. The following companion documents provide further detail on specific aspects of the Monde payment system:'),
  bullet('02 - Business Plan with Three-Year Financial Projections'),
  bullet('03 - Customer Onboarding and CDD Procedures'),
  bullet('04 - Settlement Process'),
  bullet('05 - Security Features and Cyber Security Policy'),
  bullet('06 - Product Pricing and Fee Structure'),
  bullet('07 - AML/CFT Policy and KYC Procedures'),
  bullet('08 - Organisational Structure'),
  bullet('09 - Customer Transaction Policies'),
  bullet('10 - Customer Funds Safeguarding'),
  bullet('11 - Governance Structure'),
  bullet('12 - Third-Party Agreements and SLAs'),
  bullet('13 - Payment System Rules'),
  bullet('14 - Risk Management Framework'),
  bullet('15 - Business Continuity and Disaster Recovery Plan'),
  bullet('16 - Complaints Handling and Resolution Policy'),
];

const doc = createDoc(sections);
await saveDoc(doc, 'docs/boz-designation/01_Product_Description_and_System_Architecture.docx');
