import { coverPage, disclaimer, heading, subheading, subsubheading, para, boldPara, bullet, richPara, createTable, pageBreak, spacer, createDoc, saveDoc, TODAY } from './doc-utils.mjs';

const sections = [
  ...coverPage('Customer Onboarding &\nCDD Procedures', 'Consumer Due Diligence and\nProcess Flow Documentation', '1.0', TODAY),
  ...disclaimer(),

  heading('1. INTRODUCTION'),
  para('This document describes the customer onboarding process for the Monde digital payment system, including the Customer Due Diligence (CDD) procedures implemented to comply with the Bank of Zambia Anti-Money Laundering Directives, the Financial Intelligence Centre Act, and the National Payment Systems Act, 2007.'),
  para('Monde is committed to ensuring that all customers are properly identified and verified before being granted access to payment services. The onboarding process is designed to balance regulatory compliance with user convenience, enabling rapid onboarding while maintaining robust identity verification controls.'),

  heading('2. CUSTOMER ONBOARDING PROCESS'),

  subheading('2.1 Overview'),
  para('The Monde customer onboarding process follows a streamlined digital-first approach. All onboarding is conducted through the Monde mobile application, which is available for download on the Google Play Store (Android) and Apple App Store (iOS). The onboarding process is designed to be completed in under 3 minutes.'),

  subheading('2.2 Step-by-Step Onboarding Flow'),

  subsubheading('Step 1: Application Download and Launch'),
  para('The prospective customer downloads the Monde application from an official app store. Upon first launch, the customer is presented with a welcome screen that describes the key features of the platform: Send and Receive money, Top Up and Withdraw, and QR Code/NFC payments. The customer taps "Get Started" to begin the registration process.'),

  subsubheading('Step 2: Provider Selection'),
  para('The customer selects their primary mobile money provider from the supported options:'),
  bullet('Airtel Money'),
  bullet('MTN Money'),
  bullet('Zamtel Kwacha'),
  para('This selection determines the default provider for top-up and withdrawal transactions and allows Monde to validate the phone number format against the selected network.'),

  subsubheading('Step 3: Personal Information Collection'),
  para('The customer provides the following mandatory information:'),
  bullet('Full Name: First name and last name (used for account identification and handle generation)'),
  bullet('Phone Number: A valid Zambian mobile phone number (used as the primary account identifier)'),
  para('The phone number must match the format of a valid Zambian number for the selected provider. The system validates the phone number prefix against known network prefixes:'),
  createTable(
    ['Provider', 'Valid Prefixes', 'Format'],
    [
      ['Airtel Money', '097x, 077x', '10 digits (0971234567)'],
      ['MTN Money', '096x, 076x', '10 digits (0961234567)'],
      ['Zamtel Kwacha', '095x, 075x', '10 digits (0951234567)'],
    ]
  ),
  spacer(),

  subsubheading('Step 4: Phone Number Verification (OTP)'),
  para('Monde sends a one-time password (OTP) to the customer provided phone number via SMS. This verification step serves two critical purposes:'),
  bullet('Identity Verification: Confirms that the customer has physical possession of the registered phone number'),
  bullet('SIM Ownership Validation: Ensures the customer is the rightful owner/user of the SIM card'),
  para('The OTP is generated and delivered through Twilio Verify, a globally recognized SMS verification service. The OTP:'),
  bullet('Is a 6-digit numeric code'),
  bullet('Expires after 10 minutes'),
  bullet('Can be re-sent if not received'),
  bullet('Is rate-limited to prevent abuse (maximum 5 attempts per phone number per hour)'),
  para('The customer enters the OTP in the application. The system verifies the code against the Twilio Verify service. If the code is correct, the customer proceeds to the next step. If incorrect, the customer may retry or request a new code.'),

  subsubheading('Step 5: PIN Creation'),
  para('The customer creates a 4-digit Personal Identification Number (PIN) that will be used to authorize all financial transactions. The PIN:'),
  bullet('Must be exactly 4 digits'),
  bullet('Is converted to a secure password using a one-way transformation before storage'),
  bullet('Is never stored in plain text on the device or server'),
  bullet('Is stored securely using Expo SecureStore (device-level encryption) for session management'),
  para('The customer confirms their PIN by entering it twice. If the entries match, the account creation proceeds.'),

  subsubheading('Step 6: Account Creation'),
  para('Upon successful verification and PIN creation, the following occurs automatically:'),
  bullet('A user account is created in the Supabase Authentication system'),
  bullet('A user profile is created in the Monde database with the provided information'),
  bullet('A unique user handle is generated in the format @firstname.lastname (with uniqueness checks)'),
  bullet('The account is assigned the default Copper tier (K100,000 balance limit, K20,000 daily limit)'),
  bullet('The account starts with a zero balance'),
  bullet('The customer is redirected to the main application dashboard'),

  pageBreak(),
  subheading('2.3 Onboarding Process Flow Diagram'),
  para('[PROCESS FLOW DIAGRAM]', { bold: true, italics: true }),
  spacer(),
  para('Customer Downloads App'),
  para('        |'),
  para('        v'),
  para('Welcome Screen (Feature Overview)'),
  para('        |'),
  para('        v'),
  para('Select Mobile Money Provider'),
  para('        |'),
  para('        v'),
  para('Enter Full Name + Phone Number'),
  para('        |'),
  para('        v'),
  para('Phone Validation (prefix check)'),
  para('        |'),
  para('    [Valid?] --No--> Show Error, Retry'),
  para('        |'),
  para('       Yes'),
  para('        |'),
  para('        v'),
  para('Send OTP via SMS (Twilio Verify)'),
  para('        |'),
  para('        v'),
  para('Customer Enters OTP'),
  para('        |'),
  para('    [Correct?] --No--> Retry (max 5 attempts)'),
  para('        |'),
  para('       Yes'),
  para('        |'),
  para('        v'),
  para('Create 4-Digit PIN (enter + confirm)'),
  para('        |'),
  para('        v'),
  para('Create Account + Profile + Handle'),
  para('        |'),
  para('        v'),
  para('Assign Copper Tier (default limits)'),
  para('        |'),
  para('        v'),
  para('Redirect to Dashboard'),
  spacer(),
  para('Note: A formal visual process flow diagram will be prepared for the Bank of Zambia submission.', { italics: true }),

  pageBreak(),
  heading('3. CUSTOMER DUE DILIGENCE (CDD) PROCEDURES'),

  subheading('3.1 CDD Framework'),
  para('Monde implements a risk-based approach to Customer Due Diligence (CDD) in line with the Bank of Zambia Anti-Money Laundering Directives and the Financial Intelligence Centre Act. The CDD framework operates at three levels:'),

  subsubheading('3.1.1 Simplified Due Diligence (SDD) - Copper Tier'),
  para('Applied to all new customers at onboarding. This level is appropriate for low-risk, low-value accounts with restricted transaction limits.'),
  para('Information collected:'),
  bullet('Full name (self-declared)'),
  bullet('Phone number (verified via OTP)'),
  bullet('Mobile money provider'),
  para('Controls applied:'),
  bullet('Maximum wallet balance: K100,000'),
  bullet('Maximum daily transactions: K20,000'),
  bullet('Phone number uniqueness check (one account per phone number)'),
  bullet('Account monitoring for suspicious activity'),

  subsubheading('3.1.2 Standard Due Diligence (CDD) - Gold Tier'),
  para('Applied when a customer requests a tier upgrade or when risk indicators trigger enhanced review. Additional information required:'),
  bullet('National Registration Card (NRC) or passport number'),
  bullet('Date of birth'),
  bullet('Physical address'),
  bullet('Source of funds declaration'),
  para('Controls applied:'),
  bullet('Maximum wallet balance: K250,000'),
  bullet('Maximum daily transactions: K50,000'),
  bullet('Identity verification against provided documents'),
  bullet('Transaction monitoring with lower thresholds'),

  subsubheading('3.1.3 Enhanced Due Diligence (EDD) - Platinum Tier'),
  para('Applied to high-value accounts, politically exposed persons (PEPs), and accounts flagged for enhanced scrutiny.'),
  bullet('All Standard CDD requirements plus:'),
  bullet('Proof of income or source of wealth'),
  bullet('Enhanced monitoring with manual review triggers'),
  bullet('Periodic review of account activity (quarterly)'),
  bullet('Senior management approval for tier upgrade'),
  para('Controls applied:'),
  bullet('Maximum wallet balance: K500,000'),
  bullet('Maximum daily transactions: K100,000'),
  bullet('Dedicated compliance review for transactions above K50,000'),

  pageBreak(),
  subheading('3.2 Ongoing Monitoring'),
  para('Monde implements continuous monitoring of all customer accounts to detect and prevent suspicious activity:'),
  bullet('Transaction Pattern Analysis: Automated monitoring of transaction patterns, including frequency, amounts, and counterparties'),
  bullet('Velocity Checks: Daily transaction limits enforced at the database level to prevent limit circumvention'),
  bullet('Circular Transaction Detection: System detects and blocks potential wash trading (e.g., agent depositing to a customer and the same customer immediately cashing out at the same agent within 24 hours)'),
  bullet('Duplicate Transaction Prevention: Same-amount transactions to the same recipient within a short timeframe trigger additional verification'),
  bullet('Frozen Account Controls: Accounts flagged for suspicious activity are immediately frozen, preventing all financial transactions pending investigation'),
  bullet('Agent Activity Monitoring: Agents are subject to additional controls including daily deposit limits per customer (maximum 3 deposits per customer per agent per day) and daily transfer caps'),

  subheading('3.3 Record Keeping'),
  para('Monde maintains comprehensive records of all customer information and transactions in compliance with regulatory requirements:'),
  bullet('Customer identification records: Retained for the duration of the account plus 7 years after account closure'),
  bullet('Transaction records: Retained for a minimum of 10 years'),
  bullet('Suspicious activity reports: Retained indefinitely'),
  bullet('All records are stored in encrypted form in the PostgreSQL database with automated backups'),

  subheading('3.4 Reporting Obligations'),
  para('Monde will fulfil all reporting obligations as required by the Financial Intelligence Centre Act:'),
  bullet('Suspicious Transaction Reports (STRs): Filed with the Financial Intelligence Centre (FIC) when suspicious activity is detected'),
  bullet('Large Transaction Reports: Filed for transactions exceeding prescribed thresholds'),
  bullet('Cash Transaction Reports: Filed for cash-in/cash-out transactions through agents exceeding prescribed thresholds'),
  bullet('Periodic reports to the Bank of Zambia as required'),

  heading('4. AGENT ONBOARDING'),
  subheading('4.1 Agent Due Diligence'),
  para('Monde agents undergo a rigorous onboarding process that includes:'),
  bullet('Business registration verification (PACRA registration for businesses)'),
  bullet('National Registration Card or passport verification'),
  bullet('Physical location verification'),
  bullet('Background screening'),
  bullet('Agent agreement execution'),
  bullet('Training on AML/CFT procedures, platform usage, and customer service'),

  subheading('4.2 Agent Status Management'),
  para('Agent status is managed exclusively by system administrators through the admin dashboard. Only administrators can:'),
  bullet('Grant agent status to a user account'),
  bullet('Revoke agent status'),
  bullet('Override agent-specific limits'),
  bullet('Review agent activity and commissions'),
  para('This ensures that agent designation follows proper approval workflows and cannot be self-assigned.'),

  heading('5. ACCOUNT MANAGEMENT'),
  subheading('5.1 Account Freezing'),
  para('Monde can freeze customer accounts in the following circumstances:'),
  bullet('Suspicious activity detected by automated monitoring systems'),
  bullet('Request from the customer (lost/stolen phone)'),
  bullet('Direction from the Bank of Zambia or Financial Intelligence Centre'),
  bullet('Court order'),
  bullet('Violation of Monde terms of service'),
  para('Frozen accounts cannot perform any financial transactions (send, receive, top-up, withdraw, cash-in, or cash-out) until the freeze is lifted by an administrator.'),

  subheading('5.2 PIN Recovery'),
  para('Customers who forget their PIN can recover access through the following process:'),
  bullet('Step 1: Customer selects "Forgot PIN" on the login screen'),
  bullet('Step 2: Customer enters their registered phone number'),
  bullet('Step 3: OTP is sent to the registered phone number for identity verification'),
  bullet('Step 4: Upon successful OTP verification, customer creates a new PIN'),
  bullet('Step 5: Account access is restored with the new PIN'),
];

const doc = createDoc(sections);
await saveDoc(doc, 'docs/boz-designation/03_Customer_Onboarding_and_CDD_Procedures.docx');
