import { coverPage, disclaimer, heading, subheading, subsubheading, para, boldPara, bullet, richPara, createTable, pageBreak, spacer, createDoc, saveDoc, TODAY } from './doc-utils.mjs';

const sections = [
  ...coverPage('Anti-Money Laundering &\nCountering Financing of Terrorism\n(AML/CFT) Policy', 'Know Your Customer (KYC)\nProcedures and Compliance Framework', '1.0', TODAY),
  ...disclaimer(),

  heading('1. POLICY STATEMENT'),
  para('Monde Limited ("Monde") is committed to the highest standards of Anti-Money Laundering (AML) and Countering the Financing of Terrorism (CFT) compliance. This policy establishes the framework, procedures, and controls that Monde implements to prevent, detect, and report money laundering, terrorist financing, and proliferation financing activities.'),
  para('This policy is developed in compliance with:'),
  bullet('The National Payment Systems Act, 2007 (NPSA)'),
  bullet('The Financial Intelligence Centre Act, 2010 (as amended)'),
  bullet('The Bank of Zambia Anti-Money Laundering Directives'),
  bullet('The Prohibition and Prevention of Money Laundering Act, 2001 (as amended)'),
  bullet('The Anti-Terrorism and Non-Proliferation Act, 2018'),
  bullet('Financial Action Task Force (FATF) Recommendations'),

  heading('2. SCOPE'),
  para('This policy applies to:'),
  bullet('All Monde employees, officers, directors, and contractors'),
  bullet('All Monde agents and their employees'),
  bullet('All customer relationships and transactions processed through the Monde platform'),
  bullet('All products and services offered by Monde'),

  heading('3. GOVERNANCE AND RESPONSIBILITIES'),

  subheading('3.1 Board of Directors'),
  bullet('Ultimate responsibility for AML/CFT compliance'),
  bullet('Approve AML/CFT policy and any amendments'),
  bullet('Ensure adequate resources are allocated for compliance'),
  bullet('Receive and review quarterly compliance reports'),

  subheading('3.2 Chief Compliance Officer (CCO)'),
  para('The CCO is the designated Money Laundering Reporting Officer (MLRO) and is responsible for:'),
  bullet('Implementing and maintaining the AML/CFT programme'),
  bullet('Filing Suspicious Transaction Reports (STRs) with the Financial Intelligence Centre (FIC)'),
  bullet('Filing Large Transaction Reports and Cash Transaction Reports as required'),
  bullet('Conducting risk assessments and updating the AML/CFT programme accordingly'),
  bullet('Ensuring staff training on AML/CFT procedures'),
  bullet('Liaising with the Bank of Zambia and FIC on compliance matters'),
  bullet('Reporting to the Board on AML/CFT compliance status'),

  subheading('3.3 All Employees'),
  bullet('Comply with this policy and all related procedures'),
  bullet('Complete mandatory AML/CFT training'),
  bullet('Report any suspicious activity to the CCO/MLRO'),
  bullet('Maintain confidentiality regarding any reports or investigations'),

  pageBreak(),
  heading('4. RISK-BASED APPROACH'),

  subheading('4.1 ML/TF Risk Assessment'),
  para('Monde conducts a comprehensive Money Laundering and Terrorist Financing (ML/TF) risk assessment that considers:'),

  subsubheading('4.1.1 Customer Risk Factors'),
  bullet('Customer type (individual, business, agent)'),
  bullet('Customer location (urban, peri-urban, rural)'),
  bullet('Transaction patterns and volumes'),
  bullet('Source of funds'),
  bullet('Politically Exposed Person (PEP) status'),
  bullet('Adverse media or sanctions screening results'),

  subsubheading('4.1.2 Product/Service Risk Factors'),
  bullet('P2P payments: Medium risk (potential for layering)'),
  bullet('Wallet top-up from mobile money: Low-medium risk (mobile money providers conduct their own KYC)'),
  bullet('Agent cash-in: Medium-high risk (cash-based, potential for structuring)'),
  bullet('Agent cash-out: Medium risk (cash-based, but initiated by verified customer)'),
  bullet('Agent-to-agent transfer: Medium risk (potential for float manipulation)'),

  subsubheading('4.1.3 Geographic Risk Factors'),
  para('Monde currently operates exclusively within Zambia. Geographic risk is assessed based on:'),
  bullet('Province and district of customer registration'),
  bullet('Cross-border proximity (border towns may have elevated risk)'),
  bullet('Known high-risk areas identified by law enforcement'),

  subheading('4.2 Risk Mitigation Controls'),
  createTable(
    ['Risk Level', 'CDD Level', 'Transaction Limits', 'Monitoring'],
    [
      ['Low', 'Simplified (Copper tier)', 'K100,000 balance / K20,000 daily', 'Automated'],
      ['Medium', 'Standard (Gold tier)', 'K250,000 balance / K50,000 daily', 'Automated + periodic review'],
      ['High', 'Enhanced (Platinum tier)', 'K500,000 balance / K100,000 daily', 'Automated + manual review'],
    ]
  ),
  spacer(),

  heading('5. KNOW YOUR CUSTOMER (KYC) PROCEDURES'),

  subheading('5.1 Customer Identification Programme'),
  para('Monde implements a tiered KYC programme aligned with the risk-based approach:'),

  subsubheading('5.1.1 Tier 1: Simplified KYC (All New Customers)'),
  para('Required information:'),
  bullet('Full legal name'),
  bullet('Zambian mobile phone number (verified via OTP)'),
  bullet('Mobile money provider'),
  para('Verification method:'),
  bullet('Phone number ownership verified through SMS OTP (Twilio Verify)'),
  bullet('Phone number validated against Zambian network prefixes'),
  bullet('One account per phone number enforced'),

  subsubheading('5.1.2 Tier 2: Standard KYC (Gold Tier Upgrade)'),
  para('Additional information required:'),
  bullet('National Registration Card (NRC) number or Passport number'),
  bullet('Date of birth'),
  bullet('Physical residential address'),
  bullet('Source of funds declaration (employment, business, remittance, other)'),
  para('Verification method:'),
  bullet('Document upload and manual verification by compliance team'),
  bullet('Cross-reference with available databases'),

  subsubheading('5.1.3 Tier 3: Enhanced KYC (Platinum Tier Upgrade)'),
  para('Additional information required:'),
  bullet('All Tier 2 requirements'),
  bullet('Proof of income (payslip, business registration, tax clearance)'),
  bullet('Proof of address (utility bill, lease agreement)'),
  bullet('Declaration of source of wealth'),
  para('Verification method:'),
  bullet('Enhanced document verification'),
  bullet('PEP and sanctions screening'),
  bullet('Senior management approval required'),
  bullet('Periodic review (quarterly)'),

  subheading('5.2 Agent KYC'),
  para('Agents undergo enhanced due diligence before activation:'),
  bullet('National Registration Card or passport'),
  bullet('Business registration documents (PACRA registration for businesses)'),
  bullet('Physical location verification (site visit)'),
  bullet('Character reference checks'),
  bullet('Police clearance certificate'),
  bullet('Agent agreement execution'),
  bullet('Mandatory AML/CFT training completion'),

  pageBreak(),
  heading('6. TRANSACTION MONITORING'),

  subheading('6.1 Automated Monitoring'),
  para('Monde implements automated transaction monitoring through database-level controls:'),
  bullet('Daily transaction limit enforcement (per account tier)'),
  bullet('Balance limit enforcement (per account tier)'),
  bullet('Circular fraud detection (agent depositing and same customer cashing out within 24 hours at same agent)'),
  bullet('Velocity controls (maximum 3 deposits/withdrawals per customer per agent per day)'),
  bullet('Agent daily transfer caps (K50,000 for agent-to-agent transfers)'),
  bullet('Duplicate transaction detection'),
  bullet('Account freeze capability for immediate intervention'),

  subheading('6.2 Suspicious Activity Indicators'),
  para('The following indicators may trigger further investigation:'),
  bullet('Transactions just below reporting thresholds (structuring)'),
  bullet('Rapid successive transactions to/from the same counterparty'),
  bullet('Multiple deposits from different agents in a short period'),
  bullet('Transactions inconsistent with the customer known profile'),
  bullet('Large cash-in deposits followed by immediate P2P transfers'),
  bullet('Multiple account attempts from the same device or phone number'),
  bullet('Customer refusal to provide required KYC documentation'),

  subheading('6.3 Manual Review Process'),
  para('When suspicious activity is detected:'),
  bullet('1. The account is flagged for review (and may be frozen if risk is high)'),
  bullet('2. The CCO/MLRO reviews the account history and transaction patterns'),
  bullet('3. Additional information may be requested from the customer'),
  bullet('4. If suspicion is confirmed, a Suspicious Transaction Report (STR) is filed with the FIC'),
  bullet('5. The account may remain frozen pending further instruction from FIC or law enforcement'),
  bullet('6. All review actions and decisions are documented'),

  heading('7. REPORTING OBLIGATIONS'),

  subheading('7.1 Suspicious Transaction Reports (STRs)'),
  para('Monde will file STRs with the Financial Intelligence Centre when:'),
  bullet('A transaction or series of transactions is suspected to involve proceeds of crime'),
  bullet('A transaction or attempted transaction appears to have no legitimate economic purpose'),
  bullet('A customer is suspected of engaging in money laundering or terrorist financing'),
  bullet('The customer refuses to provide required identification or documentation'),
  para('STRs will be filed promptly and within the timeframes prescribed by the FIC.'),

  subheading('7.2 Large Transaction Reports'),
  para('Monde will file reports for transactions exceeding thresholds prescribed by the Bank of Zambia and FIC. The current threshold and reporting procedures will be implemented as directed by the regulatory authorities.'),

  subheading('7.3 Cash Transaction Reports'),
  para('Agent cash-in and cash-out transactions exceeding prescribed thresholds will be reported to the FIC as required.'),

  subheading('7.4 Tipping-Off Prohibition'),
  para('Monde employees and agents are strictly prohibited from disclosing to any person (including the customer) that an STR has been filed or that an investigation is being conducted. Violation of this prohibition is a criminal offence under the Financial Intelligence Centre Act.'),

  pageBreak(),
  heading('8. SANCTIONS SCREENING'),
  para('Monde will implement screening against:'),
  bullet('United Nations Security Council Consolidated Sanctions List'),
  bullet('Financial Intelligence Centre designated persons list'),
  bullet('Any other sanctions lists as directed by the Bank of Zambia'),
  para('Screening will be conducted:'),
  bullet('At customer onboarding (for Gold and Platinum tier upgrades)'),
  bullet('Periodically for all existing customers (quarterly)'),
  bullet('When sanctions lists are updated'),

  heading('9. RECORD KEEPING'),
  para('Monde maintains the following records in compliance with regulatory requirements:'),
  bullet('Customer identification records: Retained for the duration of the business relationship plus 7 years after account closure'),
  bullet('Transaction records: Retained for a minimum of 10 years from the date of the transaction'),
  bullet('STRs and related documentation: Retained indefinitely'),
  bullet('Internal investigation records: Retained for a minimum of 10 years'),
  bullet('Training records: Retained for the duration of employment plus 5 years'),
  para('All records are stored in encrypted form in the Monde database with automated backups and are available for inspection by the Bank of Zambia, FIC, and other authorised bodies upon request.'),

  heading('10. STAFF TRAINING'),
  subheading('10.1 Training Programme'),
  para('All Monde employees and agents are required to complete AML/CFT training:'),
  bullet('Initial Training: Within 30 days of employment/engagement, covering AML/CFT laws, this policy, red flags, and reporting procedures'),
  bullet('Annual Refresher: All staff complete annual refresher training'),
  bullet('Role-Specific Training: Additional training for staff in high-risk roles (compliance, customer service, agent management)'),
  bullet('Agent Training: All agents complete mandatory training before activation, covering AML/CFT obligations, customer identification requirements, and reporting procedures'),

  subheading('10.2 Training Records'),
  para('Records of all training sessions are maintained, including:'),
  bullet('Date and content of training'),
  bullet('Names and roles of attendees'),
  bullet('Assessment results (where applicable)'),
  bullet('Trainer qualifications'),

  heading('11. POLICY REVIEW AND UPDATES'),
  para('This AML/CFT policy will be reviewed:'),
  bullet('Annually by the CCO and approved by the Board of Directors'),
  bullet('Whenever there are material changes to AML/CFT laws or regulations'),
  bullet('Following any significant compliance incident or regulatory finding'),
  bullet('When new products or services are introduced'),
  bullet('When the risk assessment identifies changes in the risk profile'),
  para('All policy updates will be communicated to staff and agents, and additional training will be provided as necessary.'),

  heading('12. COMPLIANCE MONITORING'),
  para('The CCO will conduct regular compliance monitoring activities:'),
  bullet('Quarterly review of transaction monitoring alerts and outcomes'),
  bullet('Annual independent audit of AML/CFT compliance'),
  bullet('Regular testing of monitoring systems and controls'),
  bullet('Agent compliance audits (at least annually for each agent)'),
  bullet('Board reporting on compliance status, STR filings, and risk assessment updates'),
];

const doc = createDoc(sections);
await saveDoc(doc, 'docs/boz-designation/07_AML_CFT_Policy_and_KYC_Procedures.docx');
