import { coverPage, disclaimer, heading, subheading, subsubheading, para, boldPara, bullet, richPara, createTable, pageBreak, spacer, createDoc, saveDoc, TODAY } from './doc-utils.mjs';

const sections = [
  ...coverPage('Security Features &\nCyber Security Policy', 'Information Security Controls\nand Cybersecurity Framework', '1.0', TODAY),
  ...disclaimer(),

  heading('1. INTRODUCTION'),
  para('This document describes the security features and cybersecurity measures implemented in the Monde digital payment system. Security is a foundational design principle of the Monde platform, with multiple layers of protection implemented across the application, infrastructure, and operational domains.'),
  para('This policy applies to all Monde systems, personnel, third-party providers, and customers. It is aligned with the Bank of Zambia regulatory requirements, ISO 27001 information security management principles, and industry best practices for financial technology applications.'),

  heading('2. SECURITY ARCHITECTURE OVERVIEW'),
  para('Monde employs a defence-in-depth security architecture with the following layers:'),
  bullet('Layer 1: Device Security — Encrypted credential storage, biometric lock support, anti-tampering measures'),
  bullet('Layer 2: Transport Security — TLS 1.3 encryption for all data in transit'),
  bullet('Layer 3: Authentication & Authorization — PIN-based auth, JWT tokens, Row-Level Security'),
  bullet('Layer 4: Application Security — Input validation, SQL injection prevention, code obfuscation'),
  bullet('Layer 5: Data Security — AES-256 encryption at rest, automated backups, access controls'),
  bullet('Layer 6: Infrastructure Security — AWS-hosted with DDoS protection, firewalls, network isolation'),
  bullet('Layer 7: Operational Security — Logging, monitoring, incident response procedures'),

  heading('3. AUTHENTICATION AND ACCESS CONTROL'),

  subheading('3.1 Customer Authentication'),
  subsubheading('3.1.1 Registration Authentication'),
  para('During registration, customer identity is verified through:'),
  bullet('Phone number verification via SMS one-time password (OTP) delivered through Twilio Verify'),
  bullet('OTP is a 6-digit code with 10-minute expiry'),
  bullet('Rate-limited to 5 verification attempts per phone number per hour'),
  bullet('One account per phone number enforced at the database level'),

  subsubheading('3.1.2 Transaction Authentication'),
  para('All financial transactions require PIN verification:'),
  bullet('4-digit PIN created during registration'),
  bullet('PIN is transformed into a secure password using a deterministic one-way function before transmission'),
  bullet('PIN is never stored in plain text — it is converted to a salted hash by the authentication service (GoTrue/Supabase Auth)'),
  bullet('PIN verification is performed against the authentication service for every transaction'),
  bullet('Maximum 5 failed PIN attempts before account lockout (configurable)'),

  subsubheading('3.1.3 Session Management'),
  para('User sessions are managed through JSON Web Tokens (JWT):'),
  bullet('Access tokens: Short-lived (1 hour), used for API authentication'),
  bullet('Refresh tokens: Longer-lived, stored in Expo SecureStore (device-level encryption)'),
  bullet('Automatic token refresh: Access tokens are transparently refreshed using the refresh token'),
  bullet('Session invalidation: Stale or compromised refresh tokens trigger automatic sign-out'),
  bullet('Single device session: Each new login invalidates previous sessions'),

  subheading('3.2 Administrative Access Control'),
  para('Administrative access to the Monde system is restricted to designated administrators:'),
  bullet('Admin status is stored as a database flag (is_admin) that can only be modified via direct database access'),
  bullet('Admin dashboard requires PIN verification before access is granted'),
  bullet('Admin operations are logged and auditable'),
  bullet('Separation of duties: The fee ledger account is a system account that cannot sign in — it exists only for fee collection'),

  subheading('3.3 Row-Level Security (RLS)'),
  para('The PostgreSQL database implements Row-Level Security policies that enforce data access controls at the database engine level:'),
  bullet('Users can only SELECT (read) their own profile and transaction records'),
  bullet('Users can only UPDATE their own profile fields (name, avatar)'),
  bullet('Transaction records are INSERT-only through server-side RPCs — users cannot directly modify transaction data'),
  bullet('Agent-specific policies restrict agent operations to authorised agent accounts'),
  bullet('Cash-out request visibility is restricted to the requesting customer and the assigned agent'),
  bullet('RLS policies are enforced regardless of the application layer, providing defence-in-depth'),

  pageBreak(),
  heading('4. DATA ENCRYPTION'),

  subheading('4.1 Encryption in Transit'),
  para('All data transmitted between the Monde mobile application and backend services is encrypted using TLS 1.3 (Transport Layer Security):'),
  bullet('HTTPS is enforced for all API communications — no unencrypted HTTP connections are permitted'),
  bullet('Supabase API endpoints use TLS 1.3 with strong cipher suites'),
  bullet('Communication with the Lipila payment gateway uses HTTPS with API key authentication'),
  bullet('SMS OTP delivery is handled by Twilio, which uses TLS for its API and SMS delivery infrastructure'),

  subheading('4.2 Encryption at Rest'),
  para('All data stored in the Monde system is encrypted at rest:'),
  bullet('PostgreSQL database: AES-256 encryption provided by AWS (Supabase infrastructure)'),
  bullet('Database backups: Encrypted using the same AES-256 standard'),
  bullet('Device storage: Sensitive data (session tokens, refresh tokens) stored in Expo SecureStore, which uses:'),
  bullet('  - Android: Android Keystore system (hardware-backed encryption when available)', 1),
  bullet('  - iOS: iOS Keychain Services (Secure Enclave when available)', 1),
  bullet('Customer PINs: Not stored in any form — only the salted bcrypt hash is stored in the authentication service'),

  subheading('4.3 API Key Security'),
  para('All API keys and secrets are managed securely:'),
  bullet('Supabase anon key: Used only for initial API access; all data access is controlled by RLS policies'),
  bullet('Lipila API keys: Stored as environment variables in Supabase Edge Functions, never embedded in client code'),
  bullet('Separate API keys for sandbox and production environments'),
  bullet('API keys are rotatable without application redeployment'),

  heading('5. APPLICATION SECURITY'),

  subheading('5.1 Input Validation and Sanitisation'),
  para('All user inputs are validated and sanitised before processing:'),
  bullet('Phone numbers: Validated against Zambian number format (10 digits with valid network prefix)'),
  bullet('Names: Sanitised to remove HTML tags, script injection characters (<>{}), and control characters'),
  bullet('Amounts: Validated for numeric range (minimum K1, maximum K50,000), non-negative, and within balance'),
  bullet('PINs: Validated as exactly 4 digits'),
  bullet('All text inputs are trimmed and normalised before storage'),

  subheading('5.2 SQL Injection Prevention'),
  para('Monde uses parameterised queries and stored procedures (RPCs) exclusively for database interactions:'),
  bullet('No dynamic SQL construction in the application layer'),
  bullet('All database operations use Supabase client library, which enforces parameterised queries'),
  bullet('Business logic is implemented in PostgreSQL functions (RPCs) that use parameterised inputs'),
  bullet('Row-Level Security provides an additional layer of defence against unauthorised data access'),

  subheading('5.3 Code Obfuscation and Tamper Protection'),
  para('The Android build of the Monde application includes the following protections:'),
  bullet('ProGuard/R8: Enabled for release builds, obfuscating Java/Kotlin code and removing unused code'),
  bullet('Resource shrinking: Enabled to remove unused resources from the APK'),
  bullet('Backup disabled: Android allowBackup is set to false, preventing ADB data extraction'),
  bullet('JavaScript bundle: Minified and bundled by Metro bundler in production builds'),
  bullet('Code signing: All release builds are signed with a private release keystore managed through EAS (Expo Application Services)'),
  bullet('Permissions minimised: Only required permissions are requested (Camera, NFC, Vibrate)'),

  subheading('5.4 Secure Communication'),
  bullet('All API calls use HTTPS with TLS 1.3'),
  bullet('Supabase client enforces HTTPS-only connections'),
  bullet('No sensitive data is transmitted via URL parameters — all sensitive data is in request bodies or headers'),
  bullet('Authentication tokens are transmitted via the Authorization header, not cookies or URL parameters'),

  pageBreak(),
  heading('6. INFRASTRUCTURE SECURITY'),

  subheading('6.1 Cloud Infrastructure'),
  para('Monde backend infrastructure is hosted on Supabase Cloud, which runs on Amazon Web Services (AWS):'),
  bullet('AWS Region: af-south-1 (Cape Town, South Africa) for low-latency Zambian access'),
  bullet('Supabase holds SOC2 Type II certification, ensuring rigorous security controls'),
  bullet('Network isolation: Each Supabase project runs in an isolated environment'),
  bullet('DDoS protection: AWS Shield and CloudFront provide protection against distributed denial-of-service attacks'),
  bullet('Web Application Firewall (WAF): Protects against common web exploits'),

  subheading('6.2 Database Security'),
  bullet('PostgreSQL database is not publicly accessible — only accessible through Supabase API gateway'),
  bullet('Connection pooling via PgBouncer prevents connection exhaustion attacks'),
  bullet('Database roles are configured with principle of least privilege'),
  bullet('Service role key (full database access) is never exposed to the client application'),
  bullet('Automated daily backups with 7-day retention'),
  bullet('Point-in-time recovery capability'),

  subheading('6.3 Edge Function Security'),
  para('Supabase Edge Functions that handle payment processing are secured:'),
  bullet('JWT verification: All Edge Functions require a valid JWT in the Authorization header (except callbacks)'),
  bullet('Callback Edge Functions (lipila-callback) implement custom verification of callback authenticity'),
  bullet('Environment variables store all secrets (API keys, service keys)'),
  bullet('Edge Functions run in isolated Deno V8 sandboxes with no filesystem access'),

  heading('7. ANTI-FRAUD CONTROLS'),

  subheading('7.1 Transaction-Level Controls'),
  bullet('Daily transaction limits enforced at the database level per account tier'),
  bullet('Balance limits enforced — no account can exceed its tier maximum balance'),
  bullet('P2P payments blocked from agent accounts (agents must use agent-specific functions)'),
  bullet('Self-service blocks: Agents cannot deposit to themselves, customers cannot cash out to themselves'),
  bullet('Frozen account enforcement: Frozen accounts are blocked from all financial operations across all RPCs'),

  subheading('7.2 Circular Fraud Detection'),
  para('The system detects and prevents potential circular fraud schemes:'),
  bullet('Cash-out requests check if the same agent deposited to the same customer within the last 24 hours'),
  bullet('This prevents agents from cycling funds to generate commission income'),

  subheading('7.3 Velocity Controls'),
  bullet('Maximum 3 deposits per customer per agent per 24-hour period'),
  bullet('Maximum 3 withdrawals per customer per agent per 24-hour period'),
  bullet('Agent-to-agent daily transfer cap of K50,000'),
  bullet('Top-up and withdrawal velocity monitored for unusual patterns'),

  subheading('7.4 Account Security'),
  bullet('One account per phone number (enforced at database and auth level)'),
  bullet('Account freezing capability for suspicious accounts'),
  bullet('Admin-only agent status management (no self-designation)'),
  bullet('Admin-only tier upgrades (no self-promotion to higher limits)'),

  pageBreak(),
  heading('8. LOGGING AND MONITORING'),

  subheading('8.1 Audit Logging'),
  para('Monde maintains comprehensive audit logs:'),
  bullet('All transaction records are immutable (INSERT-only, no UPDATE or DELETE)'),
  bullet('All fee records are stored in a dedicated monde_fees table'),
  bullet('Authentication events (sign-in, sign-out, failed attempts) are logged by Supabase Auth'),
  bullet('API access logs are maintained by Supabase with request metadata'),
  bullet('Admin operations are logged and associated with the admin user ID'),

  subheading('8.2 Production Logging Security'),
  para('Monde implements strict controls on production logging to prevent sensitive data leakage:'),
  bullet('All console.log, console.warn, and console.error statements are wrapped in __DEV__ guards'),
  bullet('In production builds, no sensitive data (tokens, phone numbers, PINs, passwords) is written to device logs'),
  bullet('Error messages in production are generic and do not expose system internals'),
  bullet('Edge Function logs are accessible only to authorised Monde administrators through the Supabase dashboard'),

  subheading('8.3 Monitoring and Alerting'),
  bullet('Supabase provides built-in monitoring for database performance, API latency, and error rates'),
  bullet('Edge Function execution logs are monitored for errors and performance degradation'),
  bullet('Authentication failure rates are monitored for brute-force detection'),
  bullet('Database connection counts and query performance are monitored'),

  heading('9. INCIDENT RESPONSE'),

  subheading('9.1 Incident Classification'),
  createTable(
    ['Severity', 'Description', 'Response Time', 'Examples'],
    [
      ['Critical (P1)', 'System-wide outage or active security breach', 'Immediate (within 15 minutes)', 'Data breach, complete service outage, unauthorised fund transfers'],
      ['High (P2)', 'Major feature unavailable or potential security issue', 'Within 1 hour', 'Payment processing failure, authentication service down'],
      ['Medium (P3)', 'Minor feature degradation', 'Within 4 hours', 'Slow response times, intermittent errors'],
      ['Low (P4)', 'Cosmetic or minor issues', 'Within 24 hours', 'UI glitches, non-critical log errors'],
    ]
  ),
  spacer(),

  subheading('9.2 Incident Response Procedure'),
  bullet('1. Detection: Incident detected through monitoring, user reports, or automated alerts'),
  bullet('2. Triage: Incident classified by severity and assigned to appropriate team member'),
  bullet('3. Containment: Immediate actions to limit impact (e.g., freeze affected accounts, disable affected service)'),
  bullet('4. Investigation: Root cause analysis using logs, database records, and system state'),
  bullet('5. Resolution: Fix implemented and deployed; affected users notified'),
  bullet('6. Recovery: Systems restored to normal operation; verification testing conducted'),
  bullet('7. Post-Incident Review: Lessons learned documented; preventive measures implemented'),
  bullet('8. Reporting: Incident report filed internally; regulatory notification if required by BoZ or FIC'),

  heading('10. PHYSICAL SECURITY'),
  para('While Monde operates primarily on cloud infrastructure, the following physical security measures apply:'),
  bullet('AWS Data Centres: Supabase infrastructure runs on AWS data centres that maintain SOC2, ISO 27001, and PCI DSS certifications with 24/7 physical security, biometric access controls, and CCTV surveillance'),
  bullet('Employee Devices: All employee devices with access to Monde systems must have full-disk encryption, screen lock, and remote wipe capability'),
  bullet('Office Security: Monde office premises (when established) will implement access controls, visitor logging, and clean desk policy'),
  bullet('Keystore Security: The Android release keystore is managed through EAS (Expo Application Services) with restricted access'),

  heading('11. POLICY REVIEW'),
  para('This Information and Cyber Security Policy shall be reviewed:'),
  bullet('Annually, or more frequently if significant changes occur'),
  bullet('Following any security incident'),
  bullet('When significant changes are made to the system architecture'),
  bullet('When new regulatory requirements are introduced'),
  para('The Chief Information Technology Officer (CITO) is responsible for maintaining and updating this policy. All changes require review and approval by the Board of Directors.'),
];

const doc = createDoc(sections);
await saveDoc(doc, 'docs/boz-designation/05_Security_Features_and_Cyber_Security_Policy.docx');
