import { coverPage, disclaimer, heading, subheading, subsubheading, para, boldPara, bullet, richPara, createTable, pageBreak, spacer, createDoc, saveDoc, TODAY } from './doc-utils.mjs';

const sections = [
  ...coverPage('Settlement Process', 'Transaction Settlement Flows\nand Reconciliation Procedures', '1.0', TODAY),
  ...disclaimer(),

  heading('1. INTRODUCTION'),
  para('This document describes the settlement processes employed by the Monde digital payment system. Settlement refers to the final transfer of value between parties in a transaction. Monde operates both internal (on-ledger) settlement for peer-to-peer transactions and external settlement through payment gateway partners for mobile money and bank card transactions.'),
  para('All settlement within the Monde system is denominated in Zambian Kwacha (ZMW). The system is designed to achieve real-time or near-real-time settlement for all transaction types.'),

  heading('2. SETTLEMENT ARCHITECTURE'),
  subheading('2.1 Internal Ledger'),
  para('Monde maintains an internal digital ledger implemented as a PostgreSQL database. Each user has a wallet balance that is updated atomically during transaction processing. Internal transactions (P2P payments, agent cash-in, agent cash-out) are settled instantly on the internal ledger through database transactions that ensure ACID (Atomicity, Consistency, Isolation, Durability) compliance.'),
  para('Key characteristics of the internal ledger:'),
  bullet('Atomic transactions: All balance updates within a single transaction are executed as an indivisible unit. Either all updates succeed, or none are applied.'),
  bullet('Consistency: Database constraints ensure that no account balance can go below zero, and all debits equal credits within any transaction.'),
  bullet('Isolation: Concurrent transactions are handled through PostgreSQL row-level locking, preventing double-spending and race conditions.'),
  bullet('Durability: All committed transactions are persisted to disk with write-ahead logging (WAL) and are backed up automatically.'),

  subheading('2.2 External Settlement'),
  para('External settlement occurs when funds enter or leave the Monde system through mobile money operators or bank transfers. External settlement is facilitated through the Lipila Payment Gateway, which acts as the intermediary between Monde and the financial service providers.'),

  subheading('2.3 Fee Ledger'),
  para('Monde maintains a dedicated fee ledger account (system account) that collects all transaction fees. This account is separate from customer funds and is used exclusively for fee collection and revenue management. The fee ledger:'),
  bullet('Receives P2P transaction fees (0.5% on amounts above K500)'),
  bullet('Receives the Monde portion of top-up fees (3% of top-up amount, net of Lipila charges)'),
  bullet('Receives the Monde portion of withdrawal fees (3% of withdrawal amount, net of Lipila charges)'),
  bullet('Receives the Monde portion of cash-out fees (30% of tiered fee)'),
  bullet('Disburses agent cash-in commissions (0.5% of deposit amount)'),
  bullet('Is reconciled daily by the finance team'),

  pageBreak(),
  heading('3. SETTLEMENT FLOWS BY TRANSACTION TYPE'),

  subheading('3.1 Person-to-Person (P2P) Payment Settlement'),
  boldPara('Settlement Type: Instant, Internal Ledger'),
  boldPara('Settlement Time: Real-time (T+0)'),
  spacer(),
  para('Process Flow:'),
  bullet('1. Sender initiates payment through the Monde app (enters recipient, amount, confirms with PIN)'),
  bullet('2. System validates: sender balance sufficiency, account status (not frozen), daily limit compliance, tier limit compliance, recipient existence'),
  bullet('3. System calculates applicable fee (0% for amounts up to K500; 0.5% for amounts above K500)'),
  bullet('4. Database transaction executes atomically:'),
  bullet('   a. Debit sender wallet: payment amount + fee', 1),
  bullet('   b. Credit recipient wallet: payment amount', 1),
  bullet('   c. Credit fee ledger: fee amount', 1),
  bullet('   d. Create transaction record for sender (type: send)', 1),
  bullet('   e. Create transaction record for recipient (type: receive)', 1),
  bullet('   f. Create fee record in monde_fees table', 1),
  bullet('5. Realtime notification sent to both sender and recipient'),
  bullet('6. Settlement is final and irrevocable'),
  spacer(),
  para('Settlement Diagram:'),
  para('Sender Wallet --[Amount + Fee]--> System'),
  para('System --[Amount]--> Recipient Wallet'),
  para('System --[Fee]--> Fee Ledger'),

  pageBreak(),
  subheading('3.2 Wallet Top-Up Settlement'),
  boldPara('Settlement Type: External (Lipila Gateway) + Internal Ledger'),
  boldPara('Settlement Time: T+0 (typically 30 seconds to 2 minutes)'),
  spacer(),
  para('Process Flow:'),
  bullet('1. User initiates top-up (selects amount and funding source)'),
  bullet('2. System creates a pending top-up transaction in the database'),
  bullet('3. Monde Edge Function sends collection request to Lipila API:'),
  bullet('   - For mobile money: Lipila initiates USSD push to user phone', 1),
  bullet('   - For card: Lipila initiates card authorization', 1),
  bullet('4. User approves the payment on their mobile money provider or card'),
  bullet('5. Lipila processes the collection and sends callback to Monde:'),
  bullet('   - Callback URL: Monde lipila-callback Edge Function', 1),
  bullet('   - Callback contains: referenceId, status (Successful/Failed), amount, accountNumber', 1),
  bullet('6. On successful callback:'),
  bullet('   a. Pending transaction is updated to confirmed status', 1),
  bullet('   b. User wallet is credited with: amount minus Monde fee (3% for mobile money; 4% for card)', 1),
  bullet('   c. Fee ledger is credited with: Monde fee portion', 1),
  bullet('7. On failed callback:'),
  bullet('   a. Pending transaction is marked as failed', 1),
  bullet('   b. No balance changes occur', 1),
  bullet('   c. User is notified of the failure', 1),
  spacer(),
  para('Settlement Diagram:'),
  para('User Mobile Money/Bank --[Amount]--> Lipila Gateway'),
  para('Lipila Gateway --[Amount - Lipila Fee]--> Monde Settlement Account'),
  para('Monde System --[Amount - Monde Fee]--> User Wallet'),
  para('Monde System --[Monde Fee - Lipila Fee]--> Fee Ledger'),
  spacer(),
  para('External Settlement: Lipila settles collected funds to Monde designated bank account on a T+1 basis. Lipila deducts its processing fee (2.5% for mobile money, 4% for card) before settlement.'),

  subheading('3.3 Wallet Withdrawal Settlement'),
  boldPara('Settlement Type: Internal Ledger + External (Lipila Gateway)'),
  boldPara('Settlement Time: T+0 (typically 30 seconds to 5 minutes)'),
  spacer(),
  para('Process Flow:'),
  bullet('1. User initiates withdrawal (selects amount and destination)'),
  bullet('2. System validates: balance sufficiency, account status, daily limits, tier limits'),
  bullet('3. System calculates fee (3% of withdrawal amount)'),
  bullet('4. Database transaction executes atomically:'),
  bullet('   a. Debit user wallet: withdrawal amount + fee', 1),
  bullet('   b. Credit fee ledger: Monde fee portion', 1),
  bullet('   c. Create withdrawal transaction record', 1),
  bullet('5. Monde Edge Function sends disbursement request to Lipila API'),
  bullet('6. Lipila processes disbursement to user mobile money or bank account'),
  bullet('7. On successful Lipila callback: transaction confirmed'),
  bullet('8. On failed Lipila callback: funds reversed to user wallet'),
  spacer(),
  para('Settlement Diagram:'),
  para('User Wallet --[Amount + Fee]--> System'),
  para('System --[Fee]--> Fee Ledger'),
  para('Monde Settlement Account --[Amount]--> Lipila Gateway'),
  para('Lipila Gateway --[Amount - Lipila Fee]--> User Mobile Money/Bank'),

  pageBreak(),
  subheading('3.4 Agent Cash-In (Deposit) Settlement'),
  boldPara('Settlement Type: Instant, Internal Ledger'),
  boldPara('Settlement Time: Real-time (T+0)'),
  spacer(),
  para('Process Flow:'),
  bullet('1. Customer presents cash to agent and provides their phone number'),
  bullet('2. Agent initiates cash-in through the Monde app (enters customer phone, amount)'),
  bullet('3. System validates: agent status, agent float balance, customer existence, customer not frozen, daily deposit limits (max 3 per customer per agent per day)'),
  bullet('4. Database transaction executes atomically:'),
  bullet('   a. Debit agent wallet: deposit amount', 1),
  bullet('   b. Credit customer wallet: deposit amount', 1),
  bullet('   c. Debit fee ledger: agent commission (0.5% of amount) — Monde pays the agent', 1),
  bullet('   d. Credit agent wallet: agent commission (0.5%)', 1),
  bullet('   e. Create transaction records for both agent and customer', 1),
  bullet('   f. Create fee record (fee_type: cashin_fee)', 1),
  bullet('5. Both agent and customer receive realtime balance updates'),
  para('Note: The customer pays no fee for cash-in deposits. The 0.5% agent commission is paid by Monde from the fee ledger as an incentive for agents to facilitate deposits.'),

  subheading('3.5 Agent Cash-Out Settlement'),
  boldPara('Settlement Type: Instant, Internal Ledger'),
  boldPara('Settlement Time: Real-time (T+0)'),
  spacer(),
  para('Process Flow:'),
  bullet('1. Customer initiates a cash-out request through the Monde app'),
  bullet('2. System validates: customer balance, account status, daily limits'),
  bullet('3. Agent confirms the cash-out and disburses physical cash'),
  bullet('4. Database transaction executes atomically:'),
  bullet('   a. Debit customer wallet: cash-out amount + tiered fee', 1),
  bullet('   b. Credit agent wallet: cash-out amount', 1),
  bullet('   c. Credit agent wallet: 70% of tiered fee (agent commission)', 1),
  bullet('   d. Credit fee ledger: 30% of tiered fee (Monde revenue)', 1),
  bullet('   e. Create transaction records for both parties', 1),
  bullet('   f. Create fee record (fee_type: cashout_fee)', 1),
  spacer(),
  para('Cash-Out Fee Schedule:'),
  createTable(
    ['Transaction Amount', 'Fee (ZMW)', 'Agent Share (70%)', 'Monde Share (30%)'],
    [
      ['K1 - K50', 'K2.50', 'K1.75', 'K0.75'],
      ['K51 - K100', 'K5.00', 'K3.50', 'K1.50'],
      ['K101 - K500', 'K10.00', 'K7.00', 'K3.00'],
      ['K501 - K1,000', 'K15.00', 'K10.50', 'K4.50'],
      ['K1,001 - K2,500', 'K20.00', 'K14.00', 'K6.00'],
      ['K2,501 - K5,000', 'K30.00', 'K21.00', 'K9.00'],
      ['K5,001 - K10,000', 'K40.00', 'K28.00', 'K12.00'],
      ['K10,001+', 'K50.00', 'K35.00', 'K15.00'],
    ]
  ),
  spacer(),

  pageBreak(),
  heading('4. RECONCILIATION PROCEDURES'),

  subheading('4.1 Internal Reconciliation'),
  para('Monde performs the following reconciliation procedures:'),
  bullet('Real-time Balance Verification: The sum of all user wallet balances plus the fee ledger balance equals the total system float at all times. This is enforced by the atomic transaction model.'),
  bullet('Daily Reconciliation: An automated process verifies that all transaction records balance (total debits equal total credits for each transaction).'),
  bullet('Fee Reconciliation: Daily verification that all fees collected match the expected fee calculations based on transaction amounts and types.'),

  subheading('4.2 External Reconciliation'),
  para('External reconciliation with the Lipila payment gateway:'),
  bullet('Daily Settlement Report: Lipila provides a daily settlement report listing all collections and disbursements processed.'),
  bullet('Callback Verification: All pending transactions are checked against received callbacks to identify any missing or delayed callbacks.'),
  bullet('Bank Statement Reconciliation: Monde bank account statements are reconciled against Lipila settlement reports on a daily basis.'),
  bullet('Discrepancy Resolution: Any discrepancies are flagged for investigation and resolved within 24 hours.'),

  subheading('4.3 Failure-to-Settle Arrangements'),
  para('In the event of settlement failure:'),
  bullet('Pending Top-Ups: If a collection callback is not received within 30 minutes, the pending transaction is marked as expired. If the collection was successful but the callback failed, reconciliation identifies the discrepancy and the user is credited manually.'),
  bullet('Failed Withdrawals: If a disbursement fails, the Lipila callback triggers an automatic reversal, crediting the user wallet with the debited amount (including fee).'),
  bullet('Gateway Downtime: If the Lipila gateway is unavailable, top-up and withdrawal services are temporarily suspended with a user-facing message. P2P payments and agent transactions continue to function as they rely only on the internal ledger.'),

  heading('5. FUND SEGREGATION'),
  para('Customer funds are held in a designated trust account separate from Monde operational funds. This ensures:'),
  bullet('Customer funds are always available for withdrawal'),
  bullet('Customer funds are not used for Monde operational expenses'),
  bullet('Customer funds are protected in the event of Monde insolvency'),
  bullet('The trust account balance always equals or exceeds the sum of all customer wallet balances'),
  para('Details of fund safeguarding arrangements are provided in the separate document: "Customer Funds Safeguarding."'),

  heading('6. SETTLEMENT TIMELINE SUMMARY'),
  createTable(
    ['Transaction Type', 'Internal Settlement', 'External Settlement', 'Total Time'],
    [
      ['P2P Payment', 'Instant (T+0)', 'N/A (internal only)', 'Instant'],
      ['Wallet Top-Up', 'On callback receipt', 'T+1 (Lipila to Monde bank)', '30s - 2min (user)'],
      ['Wallet Withdrawal', 'Instant (T+0)', 'T+0 (Lipila to user)', '30s - 5min (user)'],
      ['Agent Cash-In', 'Instant (T+0)', 'N/A (internal only)', 'Instant'],
      ['Agent Cash-Out', 'Instant (T+0)', 'N/A (internal only)', 'Instant'],
    ]
  ),
];

const doc = createDoc(sections);
await saveDoc(doc, 'docs/boz-designation/04_Settlement_Process.docx');
